### ISSUE TITLE
[Android] request and use a unique beacon target callsign for kv4p HT

### ISSUE THREAD

**Issue by VanceVagell** [VanceVagell/kv4p-ht#223]
Apparently use of BEACON as the recipient is obsolete and we're supposed to request and use a radio specific destination to use instead. We can request one here:

https://github.com/aprsorg/aprs-deviceid/blob/main/ALLOCATING.md

And then the Android app needs to be updated to use our specific beaconing dest.

The nice thing is this will make it easier to see how many people are using our project with beaconing.

**Comment by brandonjank** [comment]
Suggestion for allocations for Android and iOS (future) per https://github.com/aprsorg/aprs-deviceid/blob/main/ALLOCATING.md

```
 - tocall: APKVPA
   vendor: KV4P-HT Project
   model: KV4P-HT Android
   class: app
   os: Android
   contact: developers@example.com
   features:
      - messaging
      - item-in-msg

 - tocall: APKVPI
   vendor: KV4P-HT Project
   model: KV4P-HT iOS
   class: app
   os: iOS
   contact: developers@example.com
   features:
      - messaging
      - item-in-msg
```
